### PR TITLE
tt2-950/adjust json serialiser

### PR DESCRIPTION
**Pull request by zaydgds**
adjust the json serialiser to respect case sensitivity, thanks @Ryan-Andrews99, @eearcher-gds

### CODE REVIEW

**Comment by eearcher-gds** [comment]
can you squash the commits?

**Comment by eearcher-gds** [comment]
do we not have any tests which check the content in athena?

**Comment by zaydgds** [comment]
> do we not have any tests which check the content in athena?

no tests as we'd need to query athena and download the data from s3 and inspects the contents. Im assuming SAL might query athena in its tests so we can take a look there

**Comment by zaydgds** [comment]
we need to also change https://github.com/govuk-one-login/txma-ticf-integration/blob/534a4f2d4b3925e41f4c7d7896ff3b352a2ee626/template.yaml#L968

**Comment by zaydgds** [comment]
> we need to also change https://github.com/govuk-one-login/txma-ticf-integration/blob/534a4f2d4b3925e41f4c7d7896ff3b352a2ee626/template.yaml#L968

created a ticket for it in the backlog

**Pull request merged**
